[package]
name = "tapciify-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["multipart"] }
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
tapciify = { version = "2", default-features = false }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = "0.3"
urlencoding = "2"
