[package]
name = "tapciify-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6", features = ["multipart"] }
image = "0.24"
serde = { version = "1.0", features = ["derive"] }
shuttle-axum = "0.23"
shuttle-runtime = "0.22"
tapciify = { git = "https://github.com/tapnisu/tapciify", rev = "3125d6ee0a103c48a19637fd9ea91f2e3a654293", version = "2.0.0", default-features = false }
tokio = "1"
tower-http = { version = "0.4", features = ["cors"] }
